@baseurl = http://localhost:8080/api/v1

### Create new user account
POST {{baseurl}}/users/register
Content-Type: application/json

{
    "name": "Jon OJ",
    "email": "jonjerry@mail.com",
    "password": "longerword"
}

### Verify user account's email address
POST {{baseurl}}/users/verify
Content-Type: application/json

{
    "email": "jonjerry@mail.com",
    "code": "772191"
}